version: "3.7"

services:
  code-server:
    hostname: code-server
    image: codercom/code-server:4.0.2
    restart: unless-stopped
    container_name: code-server
    volumes:
      - ~/coder-volume:/home/coder
    ports:
      - "8080:8080"
    environment:
      # INITIAL_PASSWORD is defined on first run, then
      # empty. Set this manually to reset the password.
      - PASSWORD=${INITIAL_PASSWORD}
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.caddy:/data
    depends_on:
      - code-server
